[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
upload_protocol = picotool

build_flags =
    -D RS485_BAUD=115200
    -D RS485_TX_PIN=0
    -D RS485_RX_PIN=1
    -D RS485_DE_RE_PIN=2
    -D SLAVE_ADDRESS=0x01
